[theme]

# Primary accent for interactive elements
primaryColor = '#1C5283'

# Background color for the main content area
backgroundColor = '#1C5283'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#B9F1C0'

# Color used for almost all text
textColor = '#FFFFFF'

# Font family for all text in the app, except code blocks
# Accepted values (serif | Arial | monospace) 
# Default: "sans serif"
font = "sans serif"