[theme]

# Primary accent for interactive elements
primaryColor = '#E74C3C'

# Background color for the main content area
backgroundColor = '#2C3E50'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#B9F1C0'

# Color used for almost all text
textColor = '#F1C40F'

# Font family for all text in the app, except code blocks
# Accepted values (serif | Arial | monospace) 
# Default: "sans serif"
font = "sans serif"